"""empty message

Revision ID: 2e440dc52351
Revises: 
Create Date: 2017-11-11 23:46:50.485586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e440dc52351'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Brain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hos_name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('registered', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Burns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hos_name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('registered', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Hospitals',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('Internal_Injury',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hos_name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('registered', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('contact', sa.String(length=13), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('specialisation', sa.String(length=100), nullable=False),
    sa.Column('availability', sa.String(length=100), nullable=False),
    sa.Column('hos_name', sa.String(length=100), nullable=True),
    sa.Column('phone_no', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['hos_name'], ['Hospitals.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dis_type', sa.String(length=100), nullable=False),
    sa.Column('ind_prof', sa.Float(), nullable=False),
    sa.Column('hosi_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['hosi_name'], ['Hospitals.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('rep_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('hospital', sa.String(length=100), nullable=True),
    sa.Column('HB', sa.String(length=10), nullable=True),
    sa.Column('SugarBM', sa.String(length=10), nullable=True),
    sa.Column('SugarAM', sa.String(length=10), nullable=True),
    sa.Column('Uric', sa.String(length=10), nullable=True),
    sa.Column('cholestrol', sa.String(length=10), nullable=True),
    sa.Column('BP', sa.String(length=7), nullable=True),
    sa.Column('issue', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('rep_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('Equipment')
    op.drop_table('Doctors')
    op.drop_table('person')
    op.drop_table('Internal_Injury')
    op.drop_table('Hospitals')
    op.drop_table('Burns')
    op.drop_table('Brain')
    # ### end Alembic commands ###
